FROM alpine:3.12
VOLUME [ “/sys/fs/cgroup” ]
RUN mkdir /temp
COPY config.sh /temp/config.sh
RUN chmod +x /temp/config.sh
RUN ./temp/config.sh
RUN echo '@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories&&\
    apk update&&\
    apk add pure-ftpd@testing="1.0.49-r2"
RUN apk add rsyslog
COPY startup.sh /
RUN chmod +x startup.sh
COPY telegraf.conf /telegraf-1.18.2/etc/telegraf/
ENTRYPOINT [ "./startup.sh" ]
