FROM alpine:3.12
EXPOSE 5050
VOLUME [ “/sys/fs/cgroup” ]
RUN  apk add lighttpd nginx php7-common php7-iconv php7-json php7-gd php7-curl php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom php7 php7-fpm php7-curl php7-json php7-mbstring php7-zip php7-gd php7-soap php7-ssh2 php7-xml php7-tokenizer php7-mysqli lighttpd php7-cgi fcgi
RUN apk update \
    && apk add --no-cache openssh-server openrc git rsync \
    && mkdir -p /run/openrc \
    && touch /run/openrc/softlevel 
RUN mkdir -p /run/nginx
RUN openrc default 
RUN rc-update
COPY default.conf /etc/nginx/conf.d
RUN apk add rsyslog
RUN rc-update add local default
COPY startup.sh /
RUN chmod +x startup.sh
RUN mkdir -p /data/
COPY wordpress /data/www
RUN apk add libc6-compat
RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.18.2_linux_amd64.tar.gz
RUN tar xf telegraf-1.18.2_linux_amd64.tar.gz
COPY telegraf.conf /telegraf-1.18.2/etc/telegraf/
ENTRYPOINT [ "./startup.sh" ]