FROM alpine:3.12
EXPOSE 5000
VOLUME [ “/sys/fs/cgroup” ]
RUN  apk add nginx php7-mysqli php7-mbstring php7-curl php7-fpm php7-xml php7-iconv php7-json php7-session
# RUN  apk add nginx php7-cli php7-fpm php7-json php7-pdo php7-mysqli php7-zip php7-gd  php7-mbstring php7-curl php7-xml php7-bcmath php7-json php7-iconv php7-session
RUN apk update \
    && apk add --no-cache openssh-server openrc git rsync \
    && mkdir -p /run/openrc \
    && touch /run/openrc/softlevel 
RUN mkdir -p /run/nginx
RUN openrc default 
RUN rc-update
COPY default.conf /etc/nginx/conf.d
RUN apk add rsyslog
RUN rc-update add local default
COPY startup.sh /
RUN chmod +x startup.sh
RUN mkdir -p /data/
COPY phpmyadmin /data/www
RUN mkdir /data/www/tmp
RUN chmod 777 /data/www/tmp
RUN apk add libc6-compat
RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.18.2_linux_amd64.tar.gz
RUN tar xf telegraf-1.18.2_linux_amd64.tar.gz
COPY telegraf.conf /telegraf-1.18.2/etc/telegraf/
COPY doctor.sh /doctor.sh
RUN chmod +x doctor.sh
ENTRYPOINT [ "./startup.sh" ]