FROM alpine:3.12
EXPOSE 80
EXPOSE 443
VOLUME [ “/sys/fs/cgroup” ]
RUN mkdir /temp
COPY config.sh /temp/config.sh
RUN chmod +x /temp/config.sh
RUN ./temp/config.sh
COPY default.conf /etc/nginx/conf.d
RUN apk add rsyslog
COPY startup.sh /
RUN chmod +x startup.sh
ENTRYPOINT [ "./startup.sh" ]