FROM alpine:3.12
VOLUME [ “/sys/fs/cgroup” ]
RUN apk update&&\
    apk add influxdb
RUN mkdir /temp
COPY config.sh /temp/config.sh
RUN chmod +x /temp/config.sh
RUN ./temp/config.sh
RUN apk add rsyslog
COPY startup.sh /
COPY telegraf.conf /telegraf-1.18.2/etc/telegraf/
RUN chmod +x startup.sh
COPY doctor.sh /doctor.sh
RUN chmod +x doctor.sh
ENTRYPOINT [ "./startup.sh" ]
