FROM alpine:3.12
EXPOSE 3306
VOLUME [ “/sys/fs/cgroup” ]
RUN apk --no-cache add mariadb mariadb-common mariadb-client
RUN apk update \
    && apk add --no-cache openssh-server openrc git rsync \
    && mkdir -p /run/openrc \
    && touch /run/openrc/softlevel 
RUN mkdir /temp
COPY config.sh /temp/config.sh
COPY start.sh /temp/start.sh
COPY wordpress.sql /temp/wordpress.sql
COPY my.cnf /etc/
RUN chmod +x /temp/config.sh
RUN chmod +x /temp/start.sh
RUN ./temp/config.sh
COPY telegraf.conf /telegraf-1.18.2/etc/telegraf/


CMD ["./temp/start.sh"]