apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata: 
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - ./doctor.sh
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
          - name: "grafana-http"
            containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: grafana
  ports:
      - name: "http"
        port: 3000
        targetPort: 3000
  type: LoadBalancer