FROM alpine:latest
EXPOSE 80
VOLUME [ “/sys/fs/cgroup” ]
RUN  apk add nginx php7 php7-fpm php7-opcache php7-gd php7-mysqli php7-zlib php7-curl
RUN apk update \
    && apk add --no-cache openssh-server openrc git rsync \
    && mkdir -p /run/openrc \
    && touch /run/openrc/softlevel 
RUN mkdir -p /run/nginx
RUN openrc default 
RUN rc-update
COPY default.conf /etc/nginx/conf.d
COPY php.ini /etc/php7/php.ini
RUN apk add rsyslog
RUN rc-update add local default
COPY startup.sh /
RUN chmod +x startup.sh
RUN mkdir -p /data/
COPY wordpress /data/www
ENTRYPOINT [ "./startup.sh" ]