FROM alpine:3.12
VOLUME [ “/sys/fs/cgroup” ]
RUN apk update
RUN mkdir /temp
COPY config.sh /temp/config.sh
RUN chmod +x /temp/config.sh
RUN ./temp/config.sh
RUN apk add rsyslog
COPY startup.sh /
RUN chmod +x startup.sh
COPY grafana.db /grafana-7.5.6/data
COPY telegraf.conf /telegraf-1.18.2/etc/telegraf/
COPY doctor.sh /doctor.sh
RUN chmod +x doctor.sh
ENTRYPOINT [ "./startup.sh" ]